name: Docker Build & Publish

on:
  # push:
  #   branches: [ "main", "master" ]
  workflow_dispatch:

env:
  # Image name: a3180623/dns-panel
  IMAGE_NAME: a3180623/dns-panel

jobs:
  quality:
    uses: ./.github/workflows/quality.yml

  build-and-push:
    needs: quality
    runs-on: ubuntu-latest
    environment: docker hub
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
