name: Build Docker Image and Upload to Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 构建 amd64
      - name: Build amd64 image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t dns-panel:amd64 \
            --output type=docker \
            .

          docker save dns-panel:amd64 -o dns-panel-amd64.tar

      # 构建 arm64
      - name: Build arm64 image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t dns-panel:arm64 \
            --output type=docker \
            .

          docker save dns-panel:arm64 -o dns-panel-arm64.tar

      # 创建 Release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dns-panel-amd64.tar
            dns-panel-arm64.tar
